import React, { useMemo, useState } from 'react';
import { estimateFrenchIncomeTax2026 } from '../../lib/french-income-tax';

type Locale = 'fr' | 'en';
interface IncomeCalculatorProps { lang?: Locale; }
const officialSimulatorUrl = 'https://simulateur-ir-ifi.impots.gouv.fr/calcul_impot/2026/simplifie/';
const bofipUrl = 'https://bofip.impots.gouv.fr/bofip/2491-PGP.html/identifiant%3DBOI-IR-LIQ-20-10-20260407';
const economieUrl = 'https://www.economie.gouv.fr/particuliers/impots-et-fiscalite/gerer-mon-impot-sur-le-revenu/comment-calculer-votre-impot-dapres-le-bareme-de-limpot-sur-le-revenu';
const messages = {
  fr: { vintage: 'Impôt 2026 sur les revenus 2025', resident: 'Pour les résidents fiscaux français.', income: 'Revenu net imposable annuel du foyer', incomeHelp: 'Utilisez le revenu net imposable pour le calcul fiscal, et non le salaire brut ou le net à payer.', shares: 'Nombre de parts fiscales', sharesHelp: 'Saisissez un nombre strictement positif, par quarts de part si nécessaire. Vérifiez les situations particulières sur le site officiel.', sharesError: 'Saisissez un nombre de parts strictement positif, par incréments de 0,25.', grossTax: 'Impôt brut estimé', averageRate: 'Taux moyen estimé', marginalRate: 'Taux marginal d’imposition', marginalHelp: 'Il s’applique seulement à la dernière tranche de revenu par part, pas à tout le revenu.', perShare: 'Revenu imposable par part', details: 'Détail par tranche', bracket: 'Tranche par part', portion: 'Part de revenu', rate: 'Taux', tax: 'Impôt', scopeTitle: 'Périmètre et limites de cette estimation', scope: 'Cette estimation applique uniquement le barème progressif de l’impôt sur le revenu au revenu net imposable et au nombre de parts saisi.', limits: 'Elle ne tient notamment pas compte du plafonnement du quotient familial, de la décote, des réductions et crédits d’impôt, du prélèvement à la source ni des situations fiscales particulières.', sourceTitle: 'Références et vérification', jurisdiction: 'Juridiction : France', source: 'Source primaire : barème DGFiP / BOFiP 2026.', checked: 'Dernière vérification : 25 septembre 2026.', official: 'Pour une estimation complète tenant compte de votre situation fiscale, utilisez le simulateur officiel de l’administration fiscale.', copy: 'Copier le résultat', copied: 'Résultat copié.', copyError: 'Copie impossible sur ce navigateur.' },
  en: { vintage: '2026 tax on 2025 income', resident: 'For French tax residents.', income: 'Household annual net taxable income', incomeHelp: 'Use net taxable income for tax calculation, not gross salary or take-home pay.', shares: 'French tax household shares', sharesHelp: 'Enter a strictly positive number, in quarter-share increments if needed. Check special situations on the official website.', sharesError: 'Enter a strictly positive number of shares in 0.25-share increments.', grossTax: 'Estimated gross income tax', averageRate: 'Estimated average rate', marginalRate: 'Marginal tax rate', marginalHelp: 'It applies only to the last income bracket per share, not to all income.', perShare: 'Taxable income per share', details: 'Bracket breakdown', bracket: 'Bracket per share', portion: 'Income in bracket', rate: 'Rate', tax: 'Tax', scopeTitle: 'Scope and limits of this estimate', scope: 'This estimate applies only the progressive French income-tax scale to entered net taxable income and tax shares.', limits: 'It does not include the family-quotient cap, low-income relief, tax reductions or credits, tax already withheld, or special tax situations.', sourceTitle: 'Sources and review', jurisdiction: 'Jurisdiction: France', source: 'Primary source: DGFiP / BOFiP 2026 tax scale.', checked: 'Last verified: 25 September 2026.', official: 'For a complete estimate that reflects your tax situation, use the official French tax administration simulator.', copy: 'Copy result', copied: 'Result copied.', copyError: 'Copy is not available in this browser.' },
};
function formatEuro(value: number, lang: Locale) { return new Intl.NumberFormat(lang === 'fr' ? 'fr-FR' : 'en-GB', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value); }
function formatRange(lower: number, upper: number | null, lang: Locale) { const number = (value: number) => new Intl.NumberFormat(lang === 'fr' ? 'fr-FR' : 'en-GB', { maximumFractionDigits: 0 }).format(value); return upper === null ? `${lang === 'fr' ? 'Au-delà de' : 'Over'} ${number(lower)} €` : `${number(lower)} € – ${number(upper)} €`; }

export default function IncomeCalculator({ lang = 'fr' }: IncomeCalculatorProps) {
  const [income, setIncome] = useState(40_000); const [shares, setShares] = useState(1); const [sharesError, setSharesError] = useState(false); const [copyState, setCopyState] = useState<'idle' | 'copied' | 'error'>('idle'); const t = messages[lang];
  const result = useMemo(() => estimateFrenchIncomeTax2026(income, shares), [income, shares]);
  const handleIncome = (value: string) => setIncome(Math.max(0, Number(value) || 0));
  const handleShares = (value: string) => { const parsed = Number(value); const isValid = Number.isFinite(parsed) && parsed > 0 && Number.isInteger(parsed * 4); setSharesError(!isValid); if (isValid) setShares(parsed); };
  const handleExport = async () => { const text = `${t.vintage}\n${t.income}: ${formatEuro(income, lang)}\n${t.shares}: ${shares}\n${t.grossTax}: ${formatEuro(result.estimatedGrossTax, lang)}\n${t.averageRate}: ${result.averageRate.toFixed(2)}%\n${t.marginalRate}: ${(result.marginalRate * 100).toFixed(0)}%`; try { await navigator.clipboard.writeText(text); setCopyState('copied'); } catch { setCopyState('error'); } window.setTimeout(() => setCopyState('idle'), 2200); };
  return <div className="mx-auto max-w-3xl space-y-6">
    <div className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-blue-950"><p className="font-semibold">{t.vintage}</p><p className="text-sm">{t.resident}</p></div>
    <div className="space-y-6 rounded-lg border border-gray-200 bg-white p-6"><div><label htmlFor="tax-income" className="mb-2 block text-sm font-semibold text-gray-900">{t.income}</label><p className="mb-2 text-sm text-gray-600">{t.incomeHelp}</p><input id="tax-income" type="number" min="0" step="100" value={income} onChange={(event) => handleIncome(event.target.value)} className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-black" /></div><div><label htmlFor="tax-shares" className="mb-2 block text-sm font-semibold text-gray-900">{t.shares}</label><p className="mb-2 text-sm text-gray-600">{t.sharesHelp}</p><input id="tax-shares" type="number" min="0.25" step="0.25" value={shares} onChange={(event) => handleShares(event.target.value)} aria-describedby={sharesError ? 'tax-shares-error' : undefined} aria-invalid={sharesError} className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-black" />{sharesError && <p id="tax-shares-error" className="mt-2 text-sm text-red-700" role="alert">{t.sharesError}</p>}</div></div>
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3" aria-live="polite"><div className="rounded-lg border border-gray-200 bg-gray-50 p-5 text-center"><p className="text-sm text-gray-600">{t.grossTax}</p><p className="mt-2 text-2xl font-bold">{formatEuro(result.estimatedGrossTax, lang)}</p></div><div className="rounded-lg border border-gray-200 bg-gray-50 p-5 text-center"><p className="text-sm text-gray-600">{t.averageRate}</p><p className="mt-2 text-2xl font-bold">{result.averageRate.toFixed(2)}%</p></div><div className="rounded-lg border border-gray-200 bg-gray-50 p-5 text-center"><p className="text-sm text-gray-600">{t.marginalRate}</p><p className="mt-2 text-2xl font-bold">{(result.marginalRate * 100).toFixed(0)}%</p><p className="mt-1 text-xs text-gray-600">{t.marginalHelp}</p></div></div>
    <p className="text-sm text-gray-700"><strong>{t.perShare}:</strong> {formatEuro(result.taxableIncomePerShare, lang)}</p>
    <div className="overflow-x-auto rounded-lg border border-gray-200 bg-white p-5"><h3 className="mb-4 font-semibold text-gray-900">{t.details}</h3><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b text-gray-600"><th className="pb-2">{t.bracket}</th><th className="pb-2">{t.portion}</th><th className="pb-2">{t.rate}</th><th className="pb-2">{t.tax}</th></tr></thead><tbody>{result.brackets.map((item) => <tr key={`${item.lowerLimit}-${item.rate}`} className="border-b last:border-0"><td className="py-2">{formatRange(item.lowerLimit, item.upperLimit, lang)}</td><td className="py-2">{formatEuro(item.taxableAmount, lang)}</td><td className="py-2">{(item.rate * 100).toFixed(0)}%</td><td className="py-2">{formatEuro(item.tax * shares, lang)}</td></tr>)}</tbody></table></div>
    <div className="rounded-lg border border-amber-300 bg-amber-50 p-5 text-sm text-amber-950"><h3 className="mb-2 font-semibold">{t.scopeTitle}</h3><p>{t.scope}</p><p className="mt-2">{t.limits}</p></div>
    <div className="rounded-lg border border-gray-200 bg-gray-50 p-5 text-sm text-gray-700"><h3 className="mb-2 font-semibold text-gray-900">{t.sourceTitle}</h3><p>{t.jurisdiction}</p><p><a className="underline" href={bofipUrl} target="_blank" rel="noreferrer">{t.source}</a></p><p><a className="underline" href={economieUrl} target="_blank" rel="noreferrer">{lang === 'fr' ? 'Source secondaire : économie.gouv.fr, explication du barème.' : 'Secondary source: economie.gouv.fr, tax-scale explanation.'}</a></p><p>{t.checked}</p><a className="mt-3 inline-block font-medium underline" href={officialSimulatorUrl} target="_blank" rel="noreferrer">{t.official}</a></div>
    <button type="button" onClick={handleExport} className="w-full rounded-lg bg-black py-3 font-semibold text-white transition-colors hover:bg-gray-900">{t.copy}</button><p className="text-center text-sm text-gray-600" aria-live="polite">{copyState === 'copied' ? t.copied : copyState === 'error' ? t.copyError : ''}</p>
  </div>;
}
